(package "straight"
         "0.1.0"
         "Next-generation package manager")

(website-url "https://github.com/radian-software/straight.el")
(keywords "extensions")

(package-file "straight.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(depends-on "emacs" "25.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
