name: CI
on:
  push:
    branches:
      - develop
      - master
  pull_request: {}
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 26.3
          - 27.2
          - 28.2
        experimental: [false]
        include:
        - os: ubuntu-latest
          emacs-version: snapshot
          experimental: true
        - os: macos-latest
          emacs-version: snapshot
          experimental: true
        - os: windows-latest
          emacs-version: snapshot
          experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Emacs
        uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Install Eask
        uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'

      - name: CI
        env:
          VERSION: ${{ matrix.emacs_version }}
        run: |
          eask compile
          eask lint checkdoc
          eask test ert ./tests/*.el
          eask lint elisp-lint
